### ISSUE TITLE
No feature_id on the pbf tile

### ISSUE THREAD

**Issue by juloaiza** [DenysMoskalenko/vt2pbf#4]
Current implementation doesn't allow  pass the feature_id as parameter from [tile.py](https://github.com/DenysMoskalenko/vt2pbf/blob/master/vt2pbf/service/tile.py) line 24. 

Function [add_feature](https://github.com/DenysMoskalenko/vt2pbf/blob/071091ff0b3fec6bd3212e22e313d89366a0c3cf/vt2pbf/service/layer.py#L23) function support the feature_id -> `def add_feature(self, feature_info: dict, feature_id: int = None)`

any idea?

**Comment by DenysMoskalenko** [comment]
Hello)
Could you please explain in which particular case you need a function id?

**Comment by juloaiza** [comment]
To build an interactive hover effects we need to a feature state (FT). FT relies on each feature having a numeric id. 

https://docs.mapbox.com/help/tutorials/create-interactive-hover-effects-with-mapbox-gl-js/

You need to assume that each feature in the vector_tile will have an id. Id is not mandatory to build the pbf

**Comment by DenysMoskalenko** [comment]
In fact, the `feature_id` parameter in the `Layer` class was a blueprint for the future. The idea was that you could use all classes and build tiles in your own way, not just with the main `vt2pbf` function.
But now I see that supporting this functionality requires a lot of refactoring. I hope to be able to do this in the future if the library is used more often.

As a hotfix solution I have added some logic which should help you with your requirements.
Check out this PR please: https://github.com/DenysMoskalenko/vt2pbf/pull/7

**Comment by juloaiza** [comment]
Thanks for your support!
